add dependencies

diff --git a/infra/dev/supervisord/entrypoint b/infra/dev/supervisord/entrypoint
--- a/infra/dev/supervisord/entrypoint
+++ b/infra/dev/supervisord/entrypoint
@@ -7,11 +7,11 @@ if ! composer install --no-interaction --optimize-autoloader --no-progress; then
     exit 1
 fi
 
-echo "-> Migrating Database..."
-if ! php bin/console doctrine:migration:migrate --no-interaction; then
-    echo "Error: Failed to migrate the database."
-    exit 1
-fi
+# echo "-> Migrating Database..."
+# if ! php bin/console doctrine:migration:migrate --no-interaction; then
+#     echo "Error: Failed to migrate the database."
+#     exit 1
+# fi
 
 echo "-> Updating Schema..."
 if ! php bin/console doctrine:schema:update --force --no-interaction; then
